spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: wltjr0419@gmail.com
    password: oczbafpedadqrojr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  security:
    access-key: ${ACCESS_KEY}
    refresh-key: ${REFRESH_KEY}
