name: Azure

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Set yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./backend/src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          
      - name: Build with Gradle
        working-directory: ./backend
        run: chmod +x ./gradlew && ./gradlew bootJar

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ./backend/build/libs/*.jar

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ secrets.AZURE_APP_NAME }}-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/build/libs/*.jar  # Path to your JAR artifact
